# Site settings
title: Mark Knudtsen
email: mark.knudtsen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/knitr-jekyll" # the subpath of your site, e.g. /blog/
url: "https://mknudtsen.github.io" # the base hostname & protocol for your site
twitter_username: mpknudtsen
github_username:  mknudtsen
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
